# Generated by Django 4.0.5 on 2022-06-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('abstract', models.CharField(blank=True, max_length=255, null=True)),
                ('tools', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='edu.project')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
